### ISSUE TITLE
O calculo para campo Mando no arquivo raw_to_tidy de 2015 está errado, não?

### ISSUE THREAD

**Issue by rodrigomaia17** [henriquepgomide/caRtola#1]
O Mando deveria ser true se o ID do clube dele fosse igual ao do TimeCasa.

**Comment by henriquepgomide** [comment]
Olá Rodrigo!
Eu inspecionarei o código. Se quiser corrigir, fique à vontade! :)
Muito obrigado!!!!

**Comment by henriquepgomide** [comment]
Consertei o problema ao usar dados de outro repositório.
