### ISSUE TITLE
Poetry como gerenciador de dependências

### ISSUE THREAD

**Issue by arnaldog12** [henriquepgomide/caRtola#101]
Atualmente, o Kedro utiliza pipfile pra gerenciamento de dependências. Porém, existem alternativas melhores e mais usadas como [Poetry][poetry]. Além disso, apesar de termos adicionados suporte a Docker recentemente (PR #97), o poetry também facilitaria o desenvolvimento local, já que o setup é mais rápido do que com Docker.

No próprio repositório do Kedro, existe uma discussão pra mudar o package manager para Poetry ([link][issue]).

[poetry]: https://github.com/python-poetry/poetry
[issue]: https://github.com/kedro-org/kedro/issues/1722

**Comment by arnaldog12** [comment]
@brendalf
você poderia ajudar aqui?

**Comment by brendalf** [comment]
Fala @arnaldog12. Consigo sim. Vou abrir um MR.

**Comment by brendalf** [comment]
We can close this one now
