### ISSUE TITLE
Pontuação zerada da primeira rodada

### ISSUE THREAD

**Issue by Romenum** [henriquepgomide/caRtola#3]
Olá!

O arquivo csv referente à rodada #1 de 2017 contem a coluna de pontuação zerada para todos os atletas. Onde se obtém os valores corretos?

**Comment by Romenum** [comment]
Acabei de perceber que a pontuação na 1ª rodada é equivalente à pontuação. rsrs
De qualquer, agradeço pelos dados das rodadas anteriores (1ª, 2ª e 3ª). Não sabia onde encontrarconsegui aqui. Obrigado! :)

**Comment by henriquepgomide** [comment]
Olá @Romenum! Muito obrigado por indicar o problema. Eu adicionei os valores da pontuação para a coluna certa no último commit. :) :+1:

**Comment by macielfjv** [comment]
Henrique, por algum motivo os dados de scout da #1 rodada 2017 estão novamente com a pontuação zerada. A pontuação total da rodada está ok, mas o scouts estão todos zerados. Arquivos “cartola_2017.csv”, “rodada-1.csv” e “cartola_aggregated.csv”. Agradeceria muito se você corrigisse novamente :)
