### ISSUE TITLE
Dados 2018 - Somente 16 scouts nas 4 primeiras rodadas

### ISSUE THREAD

**Issue by Romenum** [henriquepgomide/caRtola#42]
Opa, Henrique! Por que as 4 primeiras rodadas só contêm dados de 16 scouts enquanto nas demais constam os 18 scouts normalmente? Pode ter havido algum erro ou é porque as informações não estão completas para estas 4 rodadas?

**Comment by henriquepgomide** [comment]
Olá @Romenum , 
As colunas PP e PD só foram disponibilizadas pela api da globo após o primeiro pênalti ser perdido e defendido. Por isso, estas colunas não estão disponíveis nas rodadas anteriores. Não há erro. Somente a forma que a Globo disponibiliza os dados.
