### ISSUE TITLE
team_data_scrapter.R - Reescrever captura dos dados dos confrontos dos times

### ISSUE THREAD

**Issue by henriquepgomide** [henriquepgomide/caRtola#45]
Bem, a CBF mudou o sistema de frontend da tabela do campeonato brasileiro. 

Precisamos agora adaptar o script para que ele capte os dados dos confrontos entre os times do campeonato brasileiro.

**Comment by joaomamorim** [comment]
Agradeço a galera pelo projeto, tá muito legal o projeto de vocês.
Referente à issue:

Por isso a tabela de partidas está desatualizada?

**Comment by henriquepgomide** [comment]
Como são poucos jogos por rodada. Por hora atualizarei na mão os resultados.

**Comment by alvinegro** [comment]
Pessoal, como ficou essa questão para esse ano? Vi que os dados da primeira rodada não tem o nome do adversário

**Comment by henriquepgomide** [comment]
@mathanssen  e @alvinegro ,
Implementei a solução proposta por @mathanssen ! Muito obrigado por apontar o site. A partir de agora os dados das rodadas estão salvos no em 'data/2019/2019_partidas'.
Abraços,
