### ISSUE TITLE
partidas_ID

### ISSUE THREAD

**Issue by joaomamorim** [henriquepgomide/caRtola#47]
Boa noite, Henrique. 

Percebi que o ano de 2017 não possui partidas_ID.csv, criei este arquivo mas não sei onde encontrar ID da rodada. Onde posso encontrar? Após ter esta informação posso fazer pull  request.

**Comment by arnaldog12** [comment]
Bom dia, @joaomamorim 

será que a gente consegue usar a coluna __game__ como id da partida nesse caso?

Se sim, sinta-se a vontade para fazer o pull request.  Caso contrário, vamos continuar discutindo como a gente pode resolver isso da melhor forma.
