### ISSUE TITLE
Problema na função rank.teams no arquivo merge_all_years.R

### ISSUE THREAD

**Issue by tdanf** [henriquepgomide/caRtola#48]
Pessoal,

Estou tentando rodar os scripts, mas estou tendo um problema que ainda não consegui resolver.

No `merge_all_years.R`, na linha 142:

> team_features <- rank.teams(scores          = matches, 
                            family          = "poisson",
                            fun             = "speedglm",
                            max.date        = round_start_date,
                            time.weight.eta = 0.01)`

O erro que aparece é o seguinte:
`Error: The scores dates are not in the same format as date.format.`

Acho estranho, porque me parece que o formato da data está certo.

Alguém já teve esse problema?

Obrigado!

**Comment by henriquepgomide** [comment]
Olá!

Vou colocar seu problema na lista de bugs. Nesta semana, irei deixar o código funcional novamente. Enquanto isso dê uma olhada neste link aqui.

https://medium.com/@hpgomide/como-montamos-defesas-no-cartolafc-com-estatística-e-modelagem-de-dados-6f5d58ac1034

Abraços,

**Comment by tdanf** [comment]
Opa, eu baixei a última versão do código e consegui rodar essa função. Acho que o problema já tinha sido resolvido. Valeu!
