### ISSUE TITLE
Scouts Rodada 1

### ISSUE THREAD

**Issue by Romenum** [henriquepgomide/caRtola#5]
A primeira rodada não possui os scouts dos jogadores?

**Comment by benschenck** [comment]
Os scouts no arquivo da segunda rodada são os dados da primeira rodada. Então falta os scouts da 2a rodada.

**Comment by henriquepgomide** [comment]
Olá @benschenck! Tentarei recuperar os dados aqui. Muito obrigado!!

**Comment by henriquepgomide** [comment]
@benschenck  e @Romenum , acho que o problema está agora resolvido. Muito obrigado por apontar o erro. :+1:
