### ISSUE TITLE
modelo preditivo em 2018

### ISSUE THREAD

**Issue by renatoluz** [henriquepgomide/caRtola#51]
Boa tarde pessoal, gostaria de saber se alguém está tocando o modelo preditivo de 2018?

Obrigado e abraços!

**Comment by henriquepgomide** [comment]
Olá Renato,
Tudo bem?

Em 2018, mantivemos apenas o download dos dados dos jogadores e partidas.

Eu, particularmente, mudei o foco do desenvolvimento dos modelos para a
criação de atributos dos times e jogadores. A principal razão é a dinâmica
do processo de escalação dos jogadores. Uma parcela significativa da
pontuação de uma escalação de uma dada rodada dos jogadores está ligada a
fatos de difícil incorporação nos modelos como : a) poupar atletas por
causa de outras competições; b) decisões táticas; c) efemeridade dos
elencos e mudanças significativas por causa de transferência.

Você tem desenvolvido alguma coisa?

Abraços,

**Comment by renatoluz** [comment]
Olá Henrique, como vai?
Obrigado pelo retorno. Não, estou apenas curioso.
Estava em busca de datasets de esporte daqui, mas acredito que ou são fechados ou simplesmente não existem.

De qualquer forma parabéns. Vou dar mais uma olhada e tentar contribuir se eu puder.

Abraços
