### ISSUE TITLE
Scouts rodada-2 2019

### ISSUE THREAD

**Issue by tuliofilho** [henriquepgomide/caRtola#59]
Os scouts da rodada 2 sumiram do csv?

**Comment by arnaldog12** [comment]
eu recuperei a versão anterior com os dados dos scouts, @tuliofilho. Pode ir lá na pasta que tá ok, agora.

**Comment by henriquepgomide** [comment]
My bad!
Valeu grande Arnaldo!

Arnaldo Gualberto <notifications@github.com> schrieb am Fr., 10. Mai 2019,
15:32:
