### ISSUE TITLE
Atualização com mercado fechado

### ISSUE THREAD

**Issue by gabriel19913** [henriquepgomide/caRtola#71]
Bom dia a todos, uma dúvida, quando o mercado está fechado os scouts na API estão null, e quando vocês fazem a atualização, os dados da rodada são subscritos e os scouts de todos os jogadores são substituído por NA, isso não é um problema? 
Porque quando o mercado reabre os dados exibidos já são da rodada 3, se não me engano.
Por que me parece que esse commit, fez exatamente isso: https://github.com/henriquepgomide/caRtola/commit/6ff778a11edb011b6a065872ead8eeecaa01f1ca

**Comment by henriquepgomide** [comment]
Olá Gabriel,
Obrigado por nos trazer atenção ao problema. Estamos trabalhando na
correção dele.
Abraço

Gabriel Aparecido Fonseca <notifications@github.com> schrieb am So., 16.
Aug. 2020, 10:47:

**Comment by henriquepgomide** [comment]
Olá @gabriel19913,

Arquivo recuperado. 

Muito obrigado!
