### ISSUE TITLE
Data 2020 rodada #7

### ISSUE THREAD

**Issue by macielfjv** [henriquepgomide/caRtola#73]
Pessoal,

alguém tem o arquivo com as estatísticas consolidadas por rodada agrupado até a rodada 7?

Agradeceria se pudesse me mandar.
Acabei indo para casa dos meus pais na pandemia e levei somente o notebook do trabalho onde estou tendo dificuldades para instalar o R. Tentei enviar o pedido como um comentário, mas acho que só consegui enviar como "issue", já peço desculpas de forma antecipada.

Abs

**Comment by henriquepgomide** [comment]
Olá @macielfjv ,
Muito obrigao por criar a issue. Problema resolvido :+1:
