### ISSUE TITLE
Dúvida - Como os dados são atualizados.

### ISSUE THREAD

**Issue by macintoxic** [henriquepgomide/caRtola#79]
Olá, na verdade fiquei com uma dúvida sobre a atualização dos dados. Como ela é feita? Dei uma olhada nos repositórios e não vi nenhuma menção.
Obrigado.

**Comment by arnaldog12** [comment]
oi, @macintoxic 
quando você diz atualização dos dados, o que você quer dizer exatamente? Como a gente pega os dados rodada a rodada, por exemplo?
Não ficou claro pra mim.

**Comment by macintoxic** [comment]
Olá @arnaldog12 , isso mesmo. Como vocês pegam os dados da rodada?
Obrigado.

**Comment by arnaldog12** [comment]
Oi, @macintoxic 
antigamente, o @henriquepgomide rodava o script `src/R/cartola_fetch.R` toda semana pra pegar os dados. Hoje, há um CI que faz isso pra gente automaticamente - que você pode conferir [aqui](https://github.com/henriquepgomide/caRtola/blob/master/.github/workflows/ci.yml).
