### ISSUE TITLE
Rodada 1 a 4 (2019) sem registro do Palmeiras

### ISSUE THREAD

**Issue by Diego-Nilson** [henriquepgomide/caRtola#82]
Nos arquivos (rodada-1.csv, rodada-2.csv, rodada-3.csv, rodada-4.csv) não há registros de jogadores do Palmeiras.

**Comment by henriquepgomide** [comment]
Não há nada a fazer aqui. O Palmeiras não participou das 4 primeiras rodadas em 2019 do Cartola por questões contratuais.
