### ISSUE TITLE
Adicionar container

### ISSUE THREAD

**Issue by RodrigoDornelles** [henriquepgomide/caRtola#89]
Seria interessante executar em containers para facilitar a preparação de um ambiente de trabalho para executar ou desenvolver o projeto.

não tenho conhecimentos em R, mas vou tentar portar para podman (docker) no linux.

fica a sugestão se alguém tiver interesse dessa melhoria.

**Comment by henriquepgomide** [comment]
Olá Rodrigo!

Eu concordo plenamente contigo. O sistema de pacotes do R e versionamento é um grande desafio para manutenção do projeto. Se quiser, podemos tentar quebrar a cabeça juntos; tenho conhecimento de R, mas nunca useu podman.

Abraço!

**Comment by RodrigoDornelles** [comment]
Podman é uma versão mais aberta de container do que docker, suporta até os mesmos arquivos de configuração e é mais extensivél de ser orquestrado.

Você pode instalar podman e podman-compose em sua maquina para testar.

vou tentar rodar o projeto aqui e te falo quais resultados tive.

**Comment by arnaldog12** [comment]
oi, @RodrigoDornelles 
adicionei recentemente suporte ao docker [nesse PR][pr97].
Pra rodar, acho mais fácil instalar o `kedro-docker` e rodar no terminal na pasta do projeto:

```sh
$ kedro docker build --image cartola
$ kedro docker run --image cartola
```

Por enquanto, ele roda o código Python. Você está mais interessado em rodar o código R?


[pr97]: https://github.com/henriquepgomide/caRtola/pull/97
