### ISSUE TITLE
Descrição de dados

### ISSUE THREAD

**Issue by lucasdcoutinh0** [henriquepgomide/caRtola#90]
Boa noite, conheci o repo a pouco tempo e estou criando uma API dele em node.js, entretanto estou com dificuldade de entender algum dos termos utilizados nas tabelas. Existe algum lugar onde possua descrição deles ?  A descrição contida dentro da pasta [Data](https://github.com/henriquepgomide/caRtola/tree/master/data) não engloba todos os termos utilizados nas tabelas das novas rodadas.

Abraços obrigado.
Caso eu posso ajudar, apenas avisem :)

**Comment by henriquepgomide** [comment]
@lucasdcoutinh0 ,

Fantástica tua iniciativa de criar uma API. Precisamos separar um tempo aqui para tentar atualizar a descrição das colunas. Devido as alterações feitas com a introdução e alteração dos scouts ao longo das temporadas, este trabalho talvez demore algum tempo.

Você já nos ajudaria tentando levantar quais são as colunas e destacar quais delas alteram ao longo do tempo. Após, eu posso criar a descrição delas e disponibilizar no LEIAME.

Muito obrigado!
Abraço!

**Comment by lucasdcoutinh0** [comment]
Valeu pela respostas, acabei de mandar um pr inserindo um readme com a descrição dos dados de 2022, 2020, 2019 e 2018, acredito que esteja tudo correto, mas vale a pena checar.

Abraços, parabéns pelo trabalho
